# Generated by Django 3.2.12 on 2023-10-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('town', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('apartment', models.IntegerField()),
                ('house_type', models.CharField(max_length=12)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('meter_reading', models.IntegerField()),
                ('address_status', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'addresses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManyToMany',
            fields=[
                ('many_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'many_to_many',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('water_meter_reading_id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateField()),
                ('fixation_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('full_name_creater', models.CharField(max_length=50)),
                ('meter_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'water_meter_reading',
                'managed': False,
            },
        ),
    ]
